/*
 * utils4j - RandomUtils.java, Aug 16, 2015 5:05:49 PM
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.varra.util;

import java.util.Random;
import java.util.UUID;

import com.varra.classification.InterfaceAudience;
import com.varra.classification.InterfaceStability;

/**
 * Related to the random utility functions.
 * 
 * @author <a href="mailto:varra@outlook.com">Rajakrishna V.
 *         Reddy</a>
 * @version 1.0
 * 
 */
@InterfaceAudience.Public
@InterfaceStability.Evolving
public final class RandomUtils
{
	
	/**
	 * Instantiates a new random utils.
	 */
	private RandomUtils()
	{
		
	}
	
	/**
	 * Uses UUID, the identifiers generated by UUID are actually universally unique identifiers. 
	 * 
	 * @return the string
	 */
	public static String uniqId()
	{
		return UUID.randomUUID().toString();
	}
	
	/**
	 * Uses {@link Random}, the passwords generated by this are mostly unique
	 * identifiers if length is &gt; 7.<br>
	 * <b>Note</b>: found one duplicate entry in 10 Lakhs of entries with
	 * password size is 8.
	 *
	 * @param length
	 *            the length
	 * @return the string
	 */
	public static String password(int length)
	{
		return RandomPasswordUtils.password(length);
	}
	
	/**
	 * Uses {@link Random}, the passwords generated by this are mostly unique
	 * identifiers if length is &gt; 7.<br>
	 * <b>Note</b>: found one duplicate entry in 10 Lakhs of entries with
	 * password size is 8.
	 *
	 * @param length
	 *            the length
	 * @return the string
	 */
	public static char[] passwordAsCharArray(int length)
	{
		return RandomPasswordUtils.passwordAsCharArray(length);
	}
}
